config/routes.rb
Rails.application.routes.draw do
  get 'bookmarks/new'
  get 'bookmarks/create'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "lists#index"

  resources :lists do
    resources :bookmarks, only: [:new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :list_id, :scope => [:movie_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create destroy]

  def index
    @bookmarks = Bookmark.all
  end

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = @list.bookmarks.new(params_bookmark)
    @bookmark.movie = Movie.find(params[:bookmark][:movie_id])
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list)
  end

  private

  def params_bookmark
    params.require(:bookmark).permit(:movie_id, :comment)
  end

  def set_list
    @list = List.find(params[:list_id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[ show edit update destroy ]

  def index
    @lists = List.all
  end

  def show
    @bookmark = Bookmark.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(params_list)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @list.update(params_list)
    redirect_to list_path(@list)

  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def params_list
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="container-sm mt-5 bg-secondary-subtle rounded-3 shadow-sm">
  <div class="m-3 p-3">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment %>
    <%= f.submit "Add bookmark", class: "btn btn-primary btn-sm" %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-dark text-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">
          <img src="<%= asset_path('logo_camera.png') %>" alt="Logo" class="d-inline-block align-top" style="width: 40px; height: 40px; object-fit: cover;">
        </a>
        <h2 class="ms-3 mb-0">
          <%= link_to "Cool app name", root_path, class: "text-decoration-none text-white" %>
        </h2>
        <%= link_to "New list", new_list_path, class: "btn btn-primary ms-3" %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="container-sm mt-5 bg-secondary-subtle rounded-3 shadow-sm">
  <div class="m-3 p-3">
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name, wrapper_html: { class: 'text-primary' } %>
    <%= f.submit class: "btn btn-primary btn-lg" %>
  <% end %>
  </div>
</div>

app/views/lists/edit.html.erb
<div>
  <%= render "form" %>
</div>

app/views/lists/index.html.erb
  <div class="banner" style="background-image: url(<%= asset_path 'theater.jpg' %>);">
    <div class="container display-3">
      <h1>Select a list...</h1>
    </div>
  </div>

<div class="container my-4">
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-md-4 mb-4">
        <div class="card shadow-sm border-0" style="width: 100%; border-radius: 8px; overflow: hidden;">
          <div class="card-category" style="background-image: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url(https://picsum.photos/300); height: 180px; background-size: cover; display: flex; align-items: center; justify-content: center;">
            <h5 class="text-center text-white" style="font-weight: bold; text-shadow: 1px 1px 5px rgba(0, 0, 0, 0.7);">
              <%= link_to list.name, list_path(list.id), class: "text-decoration-none text-white" %>
            </h5>
          </div>
          <div class="card-body">
            <div class="d-flex justify-content-between">
              <%= link_to "Edit", edit_list_path(list), class: "btn btn-sm btn-outline-primary" %>
              <%= link_to "Remove", list_path(list), class: "btn btn-sm btn-outline-danger",
                  data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div>
  <%= render "form" %>
</div>

app/views/lists/show.html.erb
<div class="container mt-5">
  <div class="text-center mb-5">
    <div class="row my-5 d-flex justify-content-between hstack">
      <div class="col-4">
        <h1 class="display-4"><%= @list.name %></h1>
      </div>
      <div class="col-4">
        <%= simple_form_for [@list, @bookmark] do |f| %>
          <%= f.association :movie %>
          <%= f.input :comment %>
          <%= f.submit "Add bookmark", class: "btn btn-primary btn-sm" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="row">
  <% @list.bookmarks.each do |bookmark| %>
    <div class="col-md-3 mb-4">
      <div class="card shadow-sm h-100 d-flex flex-column">
        <img src="<%= bookmark.movie.poster_url %>" class="card-img-top" alt="<%= bookmark.movie.title %> poster" style="height: 250px; object-fit: cover;">

        <div class="card-body flex-grow-1 d-flex flex-column">
          <h5 class="card-title"><%= bookmark.movie.title %></h5>
          <p class="card-text mb-3"><%= truncate(bookmark.movie.overview, length: 80) %></p>
          <p class="text-muted mb-1 mt-auto"><i class="fa-solid fa-star"></i> <%= bookmark.movie.rating %>/10</p>
          <p class="text-muted"><i class="fa-solid fa-comment"></i> <%= bookmark.comment %></p>
        </div>

        <div class="card-footer">
          <%= link_to "Remove",
              list_bookmark_path(@list, bookmark),
              data: {turbo_method: :delete, turbo_confirm: "Are you sure?"},
              class: "btn btn-outline-danger btn-sm" %>
        </div>
      </div>
    </div>
   <% end %>
  </div>
</div>